### ISSUE TITLE
Issue on install

### ISSUE THREAD

**Issue by Skipper-is** [borysiasty/pointsamplingtool#10]
Issue when installing and enabling PointSamplingTool, it flags this up:
`Couldn't load plugin 'pointsamplingtool' due to an error when calling its classFactory() method
    **NameError: name 'QDialog' is not defined** `

QGIS 3.1 (Nightly Build) on Windows 10 machine.

Full log:
`Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/skipp/AppData/Roaming/QGIS/QGIS3\profiles\Skipper/python/plugins\pointsamplingtool\__init__.py", line 31, in classFactory
    from .pointSamplingTool import pointSamplingTool
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/skipp/AppData/Roaming/QGIS/QGIS3\profiles\Skipper/python/plugins\pointsamplingtool\pointSamplingTool.py", line 27, in 
    from . import doPointSamplingTool
  File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/skipp/AppData/Roaming/QGIS/QGIS3\profiles\Skipper/python/plugins\pointsamplingtool\doPointSamplingTool.py", line 32, in 
    class Dialog(QDialog, Ui_Dialog):
NameError: name 'QDialog' is not defined`

**Comment by borysiasty** [comment]
Fixed in 0.5.1 (you may need to turn the plugin off and on if the manager fails to reload it automatically).
Thanks for the report!
